<?php
namespace php_active_record;
/**/
use \AllowDynamicProperties; //for PHP 8.2
#[AllowDynamicProperties] //for PHP 8.2
class ZenodoTraitBankAPI
{
    function __construct($folder = null, $query = null)
    {
        $this->download_options = array(
            'resource_id'        => 'zenodo',  //resource_id here is just a folder name in cache
            'expire_seconds'     => 60*60*24*1, //maybe 1 day to expire
            'download_wait_time' => 1000000, 'timeout' => 60*3, 'download_attempts' => 1, 'delay_in_minutes' => 0.5);
        $this->api['domain'] = 'https://zenodo.org';
    }
    function do_zenodo_stuff($concept_id)
    {
        print_r($this->param);
        // Step 1: get latest Zenodo record info (cached) using the concept ID
        if(!($arr = $this->get_zenodo_info_using_conceptID($concept_id))) exit("\nERROR: Cannot get Zenodo info.\n");
        print_r($arr);
        // Step 2: download the record's zip archive to TB_files/[record_id].zip
        if(!($zip_file = $this->download_zenodo_zip_file($arr['archive_url']))) exit("\nERROR: Cannot download Zenodo zip file.\n");
        // Step 3: extract to TB_files/[record_id]/input_files/ -- only after a fresh download,
        //         or if input_files/ is missing or empty (e.g. it was deleted manually)
        $input_dir = dirname($zip_file) . "/" . pathinfo($zip_file, PATHINFO_FILENAME) . "/input_files/";
        if($this->zip_freshly_downloaded || !is_dir($input_dir) || count(scandir($input_dir)) <= 2) {
            if(!($this->input_dir = $this->unzip_zenodo_zip_file($zip_file))) exit("\nERROR: Cannot extract Zenodo zip file.\n");
        }
        else {
            echo "No fresh download, will use existing extracted files.\n";
            $this->input_dir = $input_dir;
        }
        echo "\nInput files folder: $this->input_dir\n";
    }
    function get_zenodo_info_using_conceptID($conceptId, $expire_seconds = null)
    {   // $expire_seconds: null = use download_options, int = cache lifetime in seconds (0 = always re-fetch), false = cache never expires
        // fallbacks: child classes (e.g. GenerateCSV_NewModel) may not call this class' constructor
        $domain = $this->api['domain'] ?? 'https://zenodo.org';
        if ($expire_seconds === null) $expire_seconds = $this->download_options['expire_seconds'] ?? 60*60*24*1;

        $options = array(
            'resource_id'       => 'zenodo', // cache goes to: DOC_ROOT . $GLOBALS['MAIN_CACHE_PATH'] . 'zenodo/'
            'expire_seconds'    => $expire_seconds,
            'timeout'           => $this->download_options['timeout'] ?? 60*3,
            'download_attempts' => 1,
            'user_agent'        => 'EOL-Zenodo-connector/1.0', // Zenodo returns HTTP 403 when User-Agent is empty
            'validation_regex'  => '"conceptrecid"'); // only use cache if it is a real Zenodo record JSON
        $body = Functions::lookup_with_cache("{$domain}/api/records/{$conceptId}/versions/latest", $options);

        if (!$body) {
            echo "Request failed for conceptID [$conceptId]\n";
            return false;
        }

        $rec = json_decode($body, true);
        if (!is_array($rec)) {
            echo "Invalid JSON response for conceptID [$conceptId]\n";
            return false;
        }

        // A. Zip of all files in the record (generated by Zenodo)
        $archiveUrl = $rec["links"]["archive"] ?? null;

        // B. Any uploaded .zip files (e.g. GitHub release archives)
        $zipFiles = [];
        foreach ($rec["files"] ?? [] as $f) {
            if (str_ends_with($f["key"], ".zip")) {
                $zipFiles[] = $f["links"]["self"];
            }
        }

        return array(
            'id'          => $rec['id'],
            'version'     => $rec['metadata']['version'] ?? null,
            'archive_url' => $archiveUrl,
            'zip_files'   => $zipFiles);
    }
    function download_zenodo_zip_file($archive_url)
    {   // e.g. https://zenodo.org/api/records/23067563/files-archive -> TB_files/23067563.zip
        if (!preg_match('#/records/(\d+)/files-archive#', (string) $archive_url, $m)) {
            echo "Invalid Zenodo archive URL [$archive_url]\n";
            return false;
        }
        $filename = "{$m[1]}.zip";
        $dir      = rtrim(CONTENT_RESOURCE_LOCAL_PATH, '/') . "/TB_files/";
        $dest     = $dir . $filename;

        $this->zip_freshly_downloaded = false; // set to true only after a successful download below
        $redownload = !empty($this->param['redownload_zip_file_YN']); // missing param = 0
        if (is_file($dest) && filesize($dest) > 0) {
            if (!$redownload) {
                echo "Zip file already exists [$filename]\n";
                return $dest;
            }
            echo "Zip file already exists, re-downloading [$filename]\n";
        }
        if (!is_dir($dir) && !mkdir($dir, 0775, true)) {
            echo "Cannot create folder [$dir]\n";
            return false;
        }

        // download to a .part file first, so an interrupted download is never mistaken for an existing zip
        $part = $dest . ".part";
        if (!($fp = fopen($part, "w"))) {
            echo "Cannot write to [$part]\n";
            return false;
        }
        $ch = curl_init($archive_url);
        curl_setopt_array($ch, [
            CURLOPT_FILE           => $fp,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_FAILONERROR    => true,
            CURLOPT_USERAGENT      => "EOL-Zenodo-connector/1.0", // Zenodo returns HTTP 403 when User-Agent is empty
            CURLOPT_CONNECTTIMEOUT => 60,
            CURLOPT_TIMEOUT        => 0, // no limit, archives can be large
        ]);
        $ok     = curl_exec($ch);
        $status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error  = curl_error($ch);
        curl_close($ch);
        fclose($fp);

        if (!$ok || $status !== 200) {
            if (is_file($part)) unlink($part);
            echo "Download failed (HTTP $status) [$archive_url]: $error\n";
            return false;
        }
        rename($part, $dest);
        $this->zip_freshly_downloaded = true;
        echo "Downloaded zip file [$filename]\n";
        return $dest;
    }
    function unzip_zenodo_zip_file($zip_file)
    {   // e.g. TB_files/23067563.zip -> TB_files/23067563/input_files/
        if (!is_file((string) $zip_file)) {
            echo "Zip file not found [$zip_file]\n";
            return false;
        }
        $record_id = pathinfo($zip_file, PATHINFO_FILENAME);
        $dest_dir  = dirname($zip_file) . "/$record_id/input_files/";

        // always start fresh: delete the destination folder and its contents, then extract
        if (is_dir($dest_dir)) {
            $items = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($dest_dir, \FilesystemIterator::SKIP_DOTS),
                \RecursiveIteratorIterator::CHILD_FIRST);
            foreach ($items as $item) {
                $item->isDir() && !$item->isLink() ? rmdir($item->getPathname()) : unlink($item->getPathname());
            }
            rmdir($dest_dir);
        }
        if (!mkdir($dest_dir, 0775, true)) {
            echo "Cannot create folder [$dest_dir]\n";
            return false;
        }

        if (class_exists('ZipArchive')) {
            $zip = new \ZipArchive();
            if (($res = $zip->open($zip_file)) !== true) {
                echo "Cannot open zip file [$zip_file], ZipArchive error code: $res\n";
                return false;
            }
            $ok = $zip->extractTo($dest_dir);
            $count = $zip->numFiles;
            $zip->close();
        }
        else { // PHP zip extension not installed (e.g. our Docker container), use the unzip command instead
            exec("unzip -o -q " . escapeshellarg($zip_file) . " -d " . escapeshellarg($dest_dir) . " 2>&1", $output, $exit_code);
            $ok = ($exit_code === 0);
            if (!$ok) echo implode("\n", $output) . "\n";
            $count = iterator_count(new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($dest_dir, \FilesystemIterator::SKIP_DOTS)));
        }

        if (!$ok) {
            echo "Failed to extract [$zip_file] to [$dest_dir]\n";
            return false;
        }

        // make extracted files readable by everyone (zip may store them as rw-------)
        $items = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dest_dir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::SELF_FIRST);
        foreach ($items as $item) {
            if ($item->isLink()) continue;
            chmod($item->getPathname(), $item->isDir() ? 0755 : 0644);
        }
        echo "Extracted $count file(s) to [$record_id/input_files/]\n";
        return $dest_dir;
    }
}
?>