<?php
namespace php_active_record;
/**/
use \AllowDynamicProperties; //for PHP 8.2
#[AllowDynamicProperties] //for PHP 8.2
class ZenodoTraitBankAPI
{
    function __construct($folder = null, $query = null)
    {
        $this->download_options = array(
            'resource_id'        => 'zenodo',  //resource_id here is just a folder name in cache
            'expire_seconds'     => 60*60*24*1, //maybe 1 day to expire
            'download_wait_time' => 1000000, 'timeout' => 60*3, 'download_attempts' => 1, 'delay_in_minutes' => 0.5);
        // $this->download_options['expire_seconds'] = 0;
        $this->download_options['expire_seconds'] = 60*60*24*30; //for eol content partners
        $this->api['domain'] = 'https://zenodo.org';
    }
    function get_zenodo_info_using_conceptID($conceptId)
    {
        // fallbacks: child classes (e.g. GenerateCSV_NewModel) may not call this class' constructor
        $domain  = $this->api['domain'] ?? 'https://zenodo.org';
        $timeout = $this->download_options['timeout'] ?? 60*3;

        $ch = curl_init("{$domain}/api/records/{$conceptId}/versions/latest");
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_USERAGENT      => "EOL-Zenodo-connector/1.0", // Zenodo returns HTTP 403 when User-Agent is empty
            CURLOPT_TIMEOUT        => $timeout,
            CURLOPT_HTTPHEADER     => ["Accept: application/json"],
            // CURLOPT_HTTPHEADER  => ["Accept: application/json", "Authorization: Bearer YOUR_TOKEN"], // restricted records
        ]);
        $body   = curl_exec($ch);
        $status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error  = curl_error($ch);
        curl_close($ch);

        if ($body === false || $status !== 200) {
            echo "Request failed (HTTP $status) for conceptID [$conceptId]: $error\n";
            return false;
        }

        $rec = json_decode($body, true);
        if (!is_array($rec)) {
            echo "Invalid JSON response for conceptID [$conceptId]\n";
            return false;
        }

        // A. Zip of all files in the record (generated by Zenodo)
        $archiveUrl = $rec["links"]["archive"] ?? null;

        // B. Any uploaded .zip files (e.g. GitHub release archives)
        $zipFiles = [];
        foreach ($rec["files"] ?? [] as $f) {
            if (str_ends_with($f["key"], ".zip")) {
                $zipFiles[] = $f["links"]["self"];
            }
        }

        return array(
            'id'          => $rec['id'],
            'version'     => $rec['metadata']['version'] ?? null,
            'archive_url' => $archiveUrl,
            'zip_files'   => $zipFiles);
    }
}
?>